default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: 5
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_app
  username: root
  password: ROOT
  socket: /var/lib/mysql/mysql.sock
  host: db
  collation: utf8mb4_general_ci
