default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: 5
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TABLE_NAME", 'my_app') %>
  username: <%= ENV.fetch("DATABASE_USER_NAME", 'db_user') %>
  password: <%= ENV.fetch("DATABASE_USER_PASSWORD", '') %>
  collation: <%= ENV.fetch("DATABASE_COLLATION", '') %>
  socket: /var/lib/mysql/mysql.sock
  host: db
