include:
  - ./backend/compose.yml
  - ./frontend/compose.yml
  - ./db/compose.yml

services:
  backend:
    depends_on:
      db:
        condition: service_healthy
  db:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
