services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORKING_DIR: ${WORKING_DIR}
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:${WORKING_DIR}
    command: sh -lc "rm -rf tmp/pids/server.pid && bundle exec rails s -p $$PORT -b '0.0.0.0'"
