services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
