services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./.data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
